### ISSUE TITLE
Support installation via Bower

### ISSUE THREAD

**Issue by webdevsuperfast** [davidjcastner/smart-media-queries#1]
@davidjcastner Great set of mixins by the way. Can you add a way to install it on Bower? Right now i'm installing it using the code `bower install git@github.com:davidjcastner/smart-media-queries.git` which is too long. Thanks! awesome work.

**Comment by davidjcastner** [comment]
@webdevsuperfast I added SMQ as a bower package, you should be able to install it with `bower install smart-media-queries`, let me know if you have any issues

**Comment by webdevsuperfast** [comment]
@davidjcastner Awesome.
